// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgiL1fuTErZHdIDwmfzhfgxN8IQJWZbcY',
    appId: '1:513691704482:web:32c0c6640c92db3d65cbfb',
    messagingSenderId: '513691704482',
    projectId: 'projects-a637c',
    authDomain: 'projects-a637c.firebaseapp.com',
    storageBucket: 'projects-a637c.appspot.com',
    measurementId: 'G-48XW3W0LQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2W1rsM1HeekPU57kTeawtsmtcNdL5MI4',
    appId: '1:513691704482:android:6902a1c67e42567665cbfb',
    messagingSenderId: '513691704482',
    projectId: 'projects-a637c',
    storageBucket: 'projects-a637c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltomKiQSK0NS7R92GjRnFliolbFyc17Y',
    appId: '1:513691704482:ios:a6ac23743842353265cbfb',
    messagingSenderId: '513691704482',
    projectId: 'projects-a637c',
    storageBucket: 'projects-a637c.appspot.com',
    iosBundleId: 'com.example.smartHomeSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltomKiQSK0NS7R92GjRnFliolbFyc17Y',
    appId: '1:513691704482:ios:6be4e2121a1b41e965cbfb',
    messagingSenderId: '513691704482',
    projectId: 'projects-a637c',
    storageBucket: 'projects-a637c.appspot.com',
    iosBundleId: 'com.example.smartHomeSafe.RunnerTests',
  );
}
